services:
  cyberthreat-telegram:
    build: .
    container_name: cyberthreat-telegram
    environment:
      - "TELEGRAM_BOT_TOKEN="
      - "TELEGRAM_BOT_USERNAME="
      - "TELEGRAM_BOT_CHAT_ID="
      - "DATABASE=postgres:5432/cyberthreat"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASS=postgres"
    ports:
      - 7000:8080
    restart: always
    networks:
      - cyberthreat

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cyberthreat
    ports:
      - 5432:5432
    networks:
      - cyberthreat
    volumes:
      - /mnt/Storage/cyberthreat/data:/var/lib/postgresql/data
networks:
  cyberthreat:
    driver: bridge